name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Install pre-requisites
        run: apk add --no-cache make jq git
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: make binaries
      - name: Tag
        run: make tag || true
        

