name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Install pre-requisites
        run: apk add --no-cache make jq git
      - name: Checkout
        uses: actions/checkout@master
      - run: git config user.name "GitHub Actions" && git config user.email "actions@users.noreply.github.com"
      - name: Build
        run: make binaries
      - name: Tag
        run: make tag || true
