name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://golang:1.13.11-alpine3.10
      - name: Install pre-requisites
        run: apk add --no-cache make jq
      - name: Build
        run: make binaries

