name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install pre-requisites
        run: |
          apk add --no-cache make jq zip curl
          curl -sLO https://github.com/sgreben/subst/releases/download/1.1.1/subst_1.1.1_linux_x86_64.zip
          unzip subst_1.1.1_linux_x86_64.zip
          mv subst /usr/local/bin
      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
