name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13.11-alpine3.10
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install pre-requisites
        run: apk add --no-cache make jq zip
      - name: Build
        run: make zip
      - name: Inject slug env vars
        uses: rlespinasse/github-slug-action@v2.x
      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.GITHUB_REF_SLUG }}
          release_name: Release ${{ env.GITHUB_REF_SLUG }}
      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_64.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_64.tar.gz
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_64.zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_64.zip
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_64.zip
          asset_content_type: application/zip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_64.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_64.tar.gz
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_32.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_32.tar.gz
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_osx_x86_32.tar.gz
          asset_content_type: application/gzip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_32.zip
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_32.zip
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_windows_x86_32.zip
          asset_content_type: application/zip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_32.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_32.tar.gz
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_x86_32.tar.gz
          asset_content_type: application/gzip

      - name: Attach aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_arm64.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_arm64.tar.gz
          asset_name: aws-secretsmanager-files_${{ env.GITHUB_REF_SLUG }}_linux_arm64.tar.gz
          asset_content_type: application/gzip
